package com.irit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
   import java.awt.event.ActionEvent;
   import java.awt.event.ActionListener;
   import javax.swing.Timer;
   import org.fourthline.cling.model.meta.LocalService;

/**
 *
 * @author rahamamane
 */
public class Chronometre extends javax.swing.JFrame {
    public enum Etat {
        INIT, SUB
    };

    private Etat etat;
    private int compteur;
    private LocalService<ChronoService> switchPowerService;


    private Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            switch (etat) {
                case INIT:
                    etat = Etat.SUB;
                    decrementeCompteur();
                    afficheCompteur();
                    timer.stop();
                    break;
                case SUB:
                    if (compteur > 0) {
                        etat = Etat.SUB;
                        timer.start();
                        decrementeCompteur();
                        afficheCompteur();
                    }else {
                        etat = Etat.INIT;
                        timer.stop();
                    }
                    break;
            }
        }
    });

    /**
     * Creates new form CompteurSimple
     */
    public Chronometre(LocalService<ChronoService> switchPowerService) {
        initComponents();
        initChronometre(switchPowerService);
    }

    public void initChronometre(LocalService<ChronoService> chronoService) {
        etat = Etat.INIT;
        this.setTitle("Chronometre");
        this.compteur = 10;
        this.switchPowerService = chronoService;
    }

    public void afficheCompteur() {
        textCompteur.setText(String.valueOf(compteur));
    }

    public void decrementeCompteur() {
        compteur--;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textCompteur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textCompteur.setFont(new java.awt.Font("Ubuntu", 1, 31)); // NOI18N
        textCompteur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textCompteur.setText("60");
        textCompteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCompteurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(textCompteur, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(textCompteur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCompteurActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                              

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField textCompteur;
    // End of variables declaration//GEN-END:variables
}
